# This file defines a reusable, default transformation pipeline.
# It only contains transform-related configurations.

train:
  - _target_: torchvision.transforms.Resize
    size: [256, 256]

  - _target_: torchvision.transforms.ToTensor

  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

validation:
  - _target_: torchvision.transforms.Resize
    size: [256, 256]
  
  - _target_: torchvision.transforms.ToTensor

  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]


test:
  - _target_: torchvision.transforms.Resize
    size: [256, 256]
  
  - _target_: torchvision.transforms.ToTensor

  - _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

 